# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: golang:1.8.0

    working_directory: /go/src/github.com/redshiftzero/scrubber
    steps:
      - checkout
      - run: go get github.com/Masterminds/glide
      - run: glide install
      #- run: CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' ./...
      - run: go test -v ./...
